---

- hosts: all
  become: true
  tasks:

  - name: frissites es apache2-php telepites
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
#        - apache2
#        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Zorin OS"]
#    when: ansible_distribution == "Debian"
