---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (deb)
    tags: always
    apt:
      upgrade: dist
      update_caches: yes
    when: ansible_distribution == ["Debian"]

- hosts: servers
  become: true
  tasks:

  - name: install applications
#    tags: deb1,curl
    apt:
      name:
        - curl
      state: latest
    when: ansible_distribution == ["Debian"]

